name: Integration
on: [pull_request]
jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: yarn run serve
          wait-on: 'http://localhost:8000'