name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Tests
        run: yarn run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint
