name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Tests
        run: yarn run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: yarn run serve
          wait-on: 'http://localhost:8000'

      # - name: Install Cypress
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: yarn run build && yarn run serve
      #     wait-on: 'http://localhost:8000'

