name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: yarn

      - name: Lint
        run: yarn run lint

      - name: Tests
        run: yarn run test

      - name: Build
        run: yarn run build

      - name: Percy Test
        uses: percy/snapshot-action@v0.1.0
        with:
          build-directory: "public/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          BUNDLE_ANALYZER_TOKEN: ${{ secrets.BUNDLE_ANALYZER_TOKEN }}
